// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHeSyx15FFW3kWxgfqbRE_fbkQODoxnlE',
    appId: '1:706907465820:web:1b3b79248b2d77cbecde99',
    messagingSenderId: '706907465820',
    projectId: 'appendly-6434c',
    authDomain: 'appendly-6434c.firebaseapp.com',
    storageBucket: 'appendly-6434c.firebasestorage.app',
    measurementId: 'G-MKP8MLLBS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrrVuQxjbryozK-rSZqzohlReYA1zX9A',
    appId: '1:706907465820:android:f652c04ca99f755eecde99',
    messagingSenderId: '706907465820',
    projectId: 'appendly-6434c',
    storageBucket: 'appendly-6434c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YbHQlxGifQ4JPYh7Mnmw21FYNZibOMM',
    appId: '1:706907465820:ios:ae88dd66e87da870ecde99',
    messagingSenderId: '706907465820',
    projectId: 'appendly-6434c',
    storageBucket: 'appendly-6434c.firebasestorage.app',
    iosBundleId: 'com.example.appendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4YbHQlxGifQ4JPYh7Mnmw21FYNZibOMM',
    appId: '1:706907465820:ios:ae88dd66e87da870ecde99',
    messagingSenderId: '706907465820',
    projectId: 'appendly-6434c',
    storageBucket: 'appendly-6434c.firebasestorage.app',
    iosBundleId: 'com.example.appendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHeSyx15FFW3kWxgfqbRE_fbkQODoxnlE',
    appId: '1:706907465820:web:7a7ee2c7560b1d0aecde99',
    messagingSenderId: '706907465820',
    projectId: 'appendly-6434c',
    authDomain: 'appendly-6434c.firebaseapp.com',
    storageBucket: 'appendly-6434c.firebasestorage.app',
    measurementId: 'G-1ZFBQRSH34',
  );
}
